language: python
python:
  - 2.7
  - 3.5
notifications:
  email: false

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/miniconda
  - export PATH=~/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION flake8 numpy scipy matplotlib nose theano mock

# Run tests
script:
  - flake8 SafeRLBench --exclude test*.py,__init__.py --ignore=E402,W503 --show-source
  - flake8 SafeRLBench --filename=__init__.py,test*.py --ignore=F,E402,W503 --show-source
  - nosetests --with-doctest SafeRLBench
