# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
python:
  - 2.7
  - 3.5
notifications:
  email: false
cache:
  directories: $HOME/.cache/pip

before_install:
  - pip install flake8 numpy scipy matplotlib nose theano mock
script:
  - flake8 SafeRLBench --exclude test*.py,__init__.py --show-source
  - flake8 SafeRLBench --filename=__init__.py,test*.py --ignore=F --show-source
  - nosetests --with-doctest SafeRLBench
