language: python

sudo: required

services:
  - docker

env:
  - PYTHON=python2
  - PYTHON=python3

# Setup docker container
install:
  - docker build -f misc/Dockerfile.${PYTHON} -t test-image .
  - docker ps -a

# Run tests
script:
  - docker run test-image flake8 SafeRLBench --exclude "test*.py,__init__.py" --ignore=E402,W503 --show-source
  - docker run test-image flake8 SafeRLBench --filename="__init__.py,test*.py" --ignore=F,E402,W503 --show-source
  - docker run test-image pydocstyle SafeRLBench --match='(?!__init__).*\.py'
  - docker run test-image nosetests --with-doctest --verbosity=2 SafeRLBench  2>&1 | grep -v "^Level 1"
