# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
python:
  - 2.7
  - 3.5
notifications:
  email: false
cache:
  directories: $HOME/.cache/pip

install:
  - pip install --upgrade pip setuptools wheel
  - pip install flake8 nose mock unittest2
  - pip install --only-binary numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install theano

script:
  - flake8 SafeRLBench --exclude test*.py,__init__.py --show-source
  - flake8 SafeRLBench --filename=__init__.py,test*.py --ignore=F --show-source
  - nosetests --with-doctest SafeRLBench
